In [1]:
import tensorflow as tf

In [5]:
t1 = [[[1,2], [3,4], [5,6]], [[7,8], [9,10], [11,12]]]
#Two metrices each of size 3 by 2. Consequently we say tensor t1 has rank 3.

In [2]:
import numpy as np

In [7]:
#List
m1 = [[1.0, 2.0], [3.0, 4.0]] 

In [11]:
#ndarray
m2 = np.array([[1.0, 2.0], [3.0, 4.0]])

In [12]:
#Tensorflow Tensor object.
m3 = tf.constant([[1.0, 2.0], [3.0, 4.0]])

In [13]:
print(type(m1))

<class 'list'>


In [14]:
print(type(m2))

<class 'numpy.ndarray'>


In [15]:
print(type(m3))

<class 'tensorflow.python.framework.ops.Tensor'>


In [16]:
t1 = tf.convert_to_tensor(m1, dtype=tf.float32)

In [17]:
t2 = tf.convert_to_tensor(m2, dtype=tf.float32)

In [18]:
t3 = tf.convert_to_tensor(m3, dtype=tf.float32)

In [21]:
print(type(t1))

<class 'tensorflow.python.framework.ops.Tensor'>


In [23]:
print(type(t2))

<class 'tensorflow.python.framework.ops.Tensor'>


In [24]:
print(type(t3))

<class 'tensorflow.python.framework.ops.Tensor'>


In [31]:
#Rank 1 Tensor
m1 = tf.constant([1., 2.]) 

In [32]:
print(m1)

Tensor("Const_6:0", shape=(2,), dtype=float32)


In [27]:
#Rank 2 Tensor
m2 = tf.constant([[1], [2]])

In [28]:
print(m2)

Tensor("Const_4:0", shape=(2, 1), dtype=int32)


In [29]:
#Rank 3 Tensor
m3 = tf.constant([ [[1,2],
[3,4],
[5,6]],
[[7,8],
[9,10],
[11,12]] ])

In [30]:
print(m3)

Tensor("Const_5:0", shape=(2, 3, 2), dtype=int32)


In [33]:
#Initialize a 500-by-500 tensor with all elements equaling 0.5.
tf.ones([500,500]) * 0.5

<tf.Tensor 'mul:0' shape=(500, 500) dtype=float32>

In [34]:
x = tf.constant([[1, 2]])

In [35]:
neg_x = tf.negative(x)

In [36]:
print(neg_x)

Tensor("Neg:0", shape=(1, 2), dtype=int32)


tf.add(x, y) -> Add two tensors of the same type, x + y
tf.subtract(x, y) -> Subtract tensors of the same type, x - y
tf.multiply(x, y) -> Multiply two tensors element-wise
tf.pow(x, y) -> Take the element-wise power of x to y
tf.exp(x) -> Equivalent to pow(e, x), where e is Euler’s number (2.718…)
tf.sqrt(x) -> Equivalent to pow(x, 0.5)
tf.div(x, y) -> Take the element-wise division of x and y
tf.truediv(x, y) -> Same as tf.div, except casts the arguments as a float
tf.floordiv(x, y) -> Same as truediv, except rounds down the final answer into an integer
tf.mod(x, y) -> Takes the element-wise remainder from division


In [37]:
from math import pi

In [39]:
mean = 0.0
sigma = 1.0
#(tf.exp(tf.negative(tf.pow(x - mean, 2.0) / (2.0 * tf.pow(sigma, 2.0)))) * (1.0 / (sigma * tf.sqrt(2.0 * pi))))

In [40]:
#Sessions
x = tf.constant([[1., 2.]])
neg_op = tf.negative(x)

In [42]:
#To execute an operation and retrieve its calculated value, TensorFlow requires a session. Only a registered session may fill the values of a Tensor object
with tf.Session() as sess:
    result = sess.run(neg_op)

In [43]:
print(result)

[[-1. -2.]]


In [44]:
#Using the Interactive Session

In [45]:
sess = tf.InteractiveSession()

In [46]:
x = tf.constant([[1., 2.]])
neg_x = tf.negative(x)

In [47]:
result = neg_x.eval()

In [48]:
print (result)

[[-1. -2.]]


In [49]:
sess.close()

In [50]:
#Logging a session
with tf.Session(config=tf.ConfigProto(log_device_placement=True)) as sess:
    result = sess.run(neg_x)

In [51]:
print(result)

[[-1. -2.]]


### Variables

In [4]:
sess = tf.InteractiveSession()
raw_data = [1., 2., 8., -1., 0., 5.5, 6., 13]
spike = tf.Variable(False)
spike.initializer.run()

In [5]:
for i in range(1, len(raw_data)):
    if raw_data[i] - raw_data[i-1] > 5:
        updater = tf.assign(spike, True)
        updater.eval()
    else:
        tf.assign(spike, False).eval()
    print("Spike", spike.eval())
sess.close()    

Spike False
Spike True
Spike False
Spike False
Spike True
Spike False
Spike True


### Saving variables (Not working)

In [10]:
sess = tf.InteractiveSession()
raw_data = [1., 2., 8., -1., 0., 5.5, 6., 13]
spikes = tf.Variable([False] * len(raw_data), name='spikes')
spikes.initializer.run()


In [16]:
for i in range(1, len(raw_data)):
    if raw_data[i] - raw_data[i-1] > 5:
        spikes_val = spikes.eval()
        spikes_val[i] = True
        updater = tf.assign(spikes, spikes_val)
        updater.eval()

save_path = saver.save(sess, "spikes.ckpt")
print("spikes data saved in file: %s" % save_path)        


sess.close()

FailedPreconditionError: Attempting to use uninitialized value spikes_2
	 [[Node: _send_spikes_2_0 = _Send[T=DT_BOOL, client_terminated=true, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=4393271706656468241, tensor_name="spikes_2:0", _device="/job:localhost/replica:0/task:0/cpu:0"](spikes_2)]]

In [26]:
raw_data = np.random.normal(10, 1, 100)
alpha = tf.constant(0.05)
curr_value = tf.placeholder(tf.float32)
prev_avg = tf.Variable(0.)

update_avg = alpha * curr_value + (1 - alpha) * prev_avg

init = tf.global_variables_initializer()

with tf.Session() as sess: 
    sess.run(init)
    for i in range(len(raw_data)):
        curr_avg = sess.run(update_avg, feed_dict={curr_value: raw_data[i]})
        sess.run(tf.assign(prev_avg, curr_avg))

In [27]:
mkdir logs

### Writing summaries to view in TensorBoard

In [32]:
raw_data = np.random.normal(10, 1, 100)
alpha = tf.constant(0.05)

curr_value = tf.placeholder(tf.float32)
prev_avg = tf.Variable(0.)
update_avg = alpha * curr_value + (1 - alpha) * prev_avg

avg_hist = tf.summary.scalar("running_average", update_avg)
value_hist = tf.summary.scalar("incoming_values", curr_value)
merged = tf.summary.merge_all()
writer = tf.summary.FileWriter("./logs")
init = tf.global_variables_initializer()

In [ ]:
with tf.Session() as sess:
    sess.run(init)
    for i in range(len(raw_data)):
        summary_str, curr_avg = sess.run([merged, update_avg], feed_dict={curr_value:raw_data[i]})
        sess.run(tf.assign(prev_avg, curr_avg))
        print(raw_data[i], curr_avg)
        writer.add_summary(summary_str, i)